{% set name = "pygrin" %}
{% set version = "0.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pygrin-{{ version }}.tar.gz
  sha256: afa45fadaa2b3b94e36165955066f3d099ea3efbd03c0dbc24cc5b6ab88bc1a0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=44
  run:
    - matplotlib-base
    - numpy
    - python >={{ python_min }}

test:
  imports:
    - pygrin
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/scottprahl/pygrin.git
  summary: Gradient Index (GRIN) Lens Calculations
  description: |
    A basic collection of routines to ray trace through graded
    index (GRIN) lenses with a parabolic radial profile.
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE.txt
  doc_url: https://pygrin.readthedocs.io/
  dev_url: https://github.com/scottprahl/pygrin

extra:
  recipe-maintainers:
    - scottprahl
